### ISSUE TITLE
wxAdditions plugin missing for current wxFB

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#234]
Current wxFormBuilder 3.5 rc1 installation (at least) for Windows misses the wxAdditions plugin.
It contains only the libwxadditions-mini.dll but not the the icons and xml files.
The current releases of wxAdditions Plugin (which is v1.14) does not work with wxFB 3.5 rc1.
wxFB submitts an error when trying to read the wxAdditions plugin.

Reported by: robekras

**Comment by aaferrari** [comment]
Reviewing the history I discovered that in [this commit](https://github.com/wxFormBuilder/wxFormBuilder/commit/e698f34c1ccc83d4cbc2337f4a9fbb813dd7ce91) the file was deleted because wxFormBuilder no longer supports wxWidgets 2.8 and the components were integrated in other parts of the code (or were removed in the case of [wxFlatNotebook](https://sourceforge.net/projects/wxflatnotebook/)), therefore version 2.9+ is needed to compile the program.
