### ISSUE TITLE
"Object properties" doesn't update

### ISSUE THREAD

**Issue by peralmered** [wxFormBuilder/wxFormBuilder#317]
The "Object properties" window (from now on "OP") has problems updating when clicking the "[+]" buttons to expand (and indeed the same when contracting).

Successful workarounds include scrolling OP, or dragging the top handle of the box below (which probably has a name, but I don't know it, sorry). I speculate that both these methods force the O/S to update the entire "OP" window, which is why they work.

Tried both v3.6.0 and the latest stable Windows build.
Windows 10 Home x64, fully update 2017-10-13, 16GB RAM.

**Comment by peralmered** [comment]
Possibly related:

After adding a wxComboBox, the Object Properties window doesn't update to reflect the settings for the ComboBox; video:

[https://youtu.be/JehiRbzUdCU?t=30](url)

**Comment by onvav** [comment]
I have observed same issue (non responsive wxFormBuilder GUI, widgets are flickering...). It is somehow caused by __wxScrolledWindow__ in combination with wxComboBox/wxChoice. When I replace wxScrolledWindos by wxPanel or when I remove all wxComboBox/wxChoice widgets, then it is OK.

- wxFormBuilder 3.6.2 (Unicode)
- Windows 7 64-bit

**Comment by bgoodmansf** [comment]
I see the same thing. I am attaching an example project which has a wxScrolledWindow containing several sizers and a choice control. Clicking on bSizer6, bSizer7 or fgSizer1 in the Object Tree panel causes the outline in the Designer panel to begin flickering and many items in the Object Properties panel become unresponsive. You cannot exit the application until you click on a different item.
[scrollfail.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/1933310/scrollfail.zip)

**Comment by onvav** [comment]
Just FYI: Still same behavior with recently released wxFormBuilder 3.7.0 (Unicode)

**Comment by pgiraudi** [comment]
Same problem with wx.ScrolledWindow. The design window flick an don't show the layaut and the properties window don't refresh well. I attach the porject
[clinik.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/5145443/clinik.zip)

**Comment by sodevel** [comment]
Same answer, wontfix, because this is not a problem of wxFB primarily but a problem of wxWidgets. I used your project with my wxFB build against some wxWidgets 3.1.x snapshot of master, there is not problem with it. Beside it is quite slow, but this is a pretty huge project file, there is no crash 😃

**Comment by pgiraudi** [comment]
So the problem is due the interaction between wxFB and wxWidgets as the program iself works fine with versions 2.8 to 4.1 of WxPython.
As you said is a huge project and I certainly could never have done it without the help of wxFB, this issue is only a detail.

**Comment by sodevel** [comment]
Basically yes. wxFB is a C++ application and the releases available from GitHub are linked against wxWidgets 3.0.x because still no newer version is available for MSYS2 and for most Linux distributions. To fix this (and other wxWidgets 3.0.x related issues) you need to compile wxFB yourself against a newer wxWidgets release.

**Comment by pgiraudi** [comment]
Okay, thanks for the suggestion.
