### ISSUE TITLE
generated code not work while using wxStaticBoxSizer

### ISSUE THREAD

**Issue by 561546441** [wxFormBuilder/wxFormBuilder#347]
Hello, I use the wxStaticBoxSizer and put a buttun in it. The generated code is as follows:

`sbSizer3 = wx.StaticBoxSizer( wx.StaticBox( self, wx.ID_ANY, u"label" ), wx.VERTICAL )
		
self.m_button5 = wx.Button( sbSizer3.GetStaticBox(), wx.ID_ANY, u"MyButton", wx.DefaultPosition, wx.DefaultSize, 0 )`

The code sbSizer3.GetStaticBox() is error.
I use sbSizer3.GetStaticBox().GetParent() Instead of it.

wxFormBuilder version: 3.6.1
g++ version: 4.9.4
os: ubuntu14.04
wx: 2.8.12.1

**Comment by attoblarg** [comment]
I know this is a problem when using wxPython 2.8.x, but it isn't with wxPython 3.0.x.  I would recommend updating if you can - when I went through this, nothing from wxFormBuilder broke and my own wx additions only required a few easy changes.

**Comment by jmagic** [comment]
Hi 561546441,

I think this is expected. wxFormBuilder is generating code for wxPython version 4.0.1
https://docs.wxpython.org/wx.StaticBoxSizer.html?highlight=getstaticbox

Since you are still using wxPython version 2.8.12.1, and you want to use wxFormBuilder, you can get an older version from here: https://sourceforge.net/projects/wxformbuilder/files/latest/download?source=files

To migrate to wxPython version 4, check out the migration guide: https://docs.wxpython.org/MigrationGuide.html
