### ISSUE TITLE
wxFB status bar shows description when selecting various properties, but it is elipsized out.

### ISSUE THREAD

**Issue by specing** [wxFormBuilder/wxFormBuilder#463]
Picture uploaded here as BadHub can't handle them: https://framapic.org/heqDSaGkFxGB/LciCPeAv4N4t.png

Furthermore, I could not find this description in full anywhere in the user interface.
At wxfb commit 359d3a3

**Comment by sodevel** [comment]
Space is limited so not everything can be displayed. For some reason the field separators are invisible on your screenshot, otherwise you could see that there is another field in the middle. This one shows the name of the current projectfile, your project doesn't seem to be saved yet so it is empty.

The displayed text is the associated help string of the currently selected item in the object inspector, these strings are defined in the xml files.

**Comment by jhasse** [comment]
> Picture uploaded here as BadHub can't handle them

Why can't GitHub handle them?

You framapic link is down.

**Comment by specing** [comment]
I did not have the required websites enabled for javascript execution. Anyway it would be better if the element/item/.. description be printed in some larger box somewhere, as it almost always gets elipsized out in the left part of statusbar (1440 pixel wide screen).

**Comment by sodevel** [comment]
The very same text is already displayed in the help box at the bottom of the object inspector (the propgrid at the right side). And if you click through certain elements you fill soon find some that fill up the whole box with multiple lines, impossible to get that into the status bar.

**Comment by specing** [comment]
Aaah yes, I had it fully minimised for some reason.
