### ISSUE TITLE
The CPP file generated when the menu contains Chinese is empty

### ISSUE THREAD

**Issue by aqtata** [wxFormBuilder/wxFormBuilder#538]
When the menu contains Chinese and the encoding attribute is ANSI, a zero-byte CPP file is generated.

My operating system is simplified Chinese.

![1](https://user-images.githubusercontent.com/11865762/63634835-84f7d180-c68e-11e9-89f9-b63f57549701.png)
![2](https://user-images.githubusercontent.com/11865762/63634836-8628fe80-c68e-11e9-85f8-a9a19718077b.png)
![3](https://user-images.githubusercontent.com/11865762/63634837-8628fe80-c68e-11e9-9eea-3cd8d1d4bc91.png)

**Comment by sodevel** [comment]
This is because ANSI is indeed ANSI, to be precise ISO 8859-1, and this cannot represent chinese characters. The string conversion functions return an empty string when invalid characters are encountered.

Just save your files in UTF-8 and the problem is gone. Recent wxWidgets versions cannot be compiled in ANSI mode any more, it's probably a good idea to remove that option.
