### ISSUE TITLE
Windows Installation via MinGW32

### ISSUE THREAD

**Issue by Performance20** [wxFormBuilder/wxFormBuilder#541]
I had the problem to update MinGW via pacman and got a lot of transfer timesouts which lead to uninstalled packages like git.

I solve it by changed the command line.
From:
pacman -S --needed mingw-w64-i686-wxWidgets git make mingw-w64-i686-binutils mingw-w64-i686-gcc mingw-w64-i686-boost

To:

pacman -S --needed --disable-download-timeout mingw-w64-i686-wxWidgets git make mingw-w64-i686-binutils mingw-w64-i686-gcc mingw-w64-i686-boost

Possible makes sense to update  the istruction

Helge

**Comment by sodevel** [comment]
I am not familiar with pacman but i don't think it is a good idea to disable download timeouts, they are in place for good reasons, otherwise installation could stall forever. I don't know what pacman states on how to solve connectivity issues, but the instructions should be kept as close as possible to a sensible default. If something doesn't work the primary documentation, pacman in this case, should be consulted.

**Comment by jhasse** [comment]
Sounds to me like temporary server issues of the MSYS2 project, not anything to do with pacman itself. Does it still happen if you try it again?

**Comment by jhasse** [comment]
Please reopen, if it still happens.
