### ISSUE TITLE
Windows Binaries are missing libzstd.dll

### ISSUE THREAD

**Issue by wlenthe** [wxFormBuilder/wxFormBuilder#542]
I couldn't run the binaries on windows until manually adding the missing library from https://github.com/facebook/zstd/releases/tag/v1.4.3

**Comment by sodevel** [comment]
Where did you get the binaries from? The releases from here don't use the facebook version of zlib but the original one and the required library is included in the installer.

**Comment by Kvaz1r** [comment]
I can reproduce the behaviour on Win10 when downloaded wxFB from link in ReadMe.

**Comment by wlenthe** [comment]
I used zstd-v1.4.3-win64/dll/libzstd.dll from the [facebook binaries ](https://github.com/facebook/zstd/releases/download/v1.4.3/zstd-v1.4.3-win32.zip)(they were the first ones I found)

**Comment by sodevel** [comment]
Looks like i've missed that link that points to some archives created by AppVeyor CI. Indeed its builds depend on the facebook zlib in addition to the "regular" one, it's a transitive dependency of the Msys2 wxWidgets binary. Don't know if this was added recently or just no one used these builds before, thanks for discovering this.

I'm not familiar with that CI nor do i use Msys2, i will try to fix that, maybe also update wxWidgets so that some other issues disappear that are not present when using wxWidgets 3.1.x.
