### ISSUE TITLE
README file does not indicate Installation requires a submodule

### ISSUE THREAD

**Issue by Randalphwa** [wxFormBuilder/wxFormBuilder#556]
For installation instructions, the README.md file contains only a header, which may lead a user to believe that all they need to do is clone the repository. However, the repository contains a required submodule, and without it the project will not build. Instructions about how to get the submodule during the initial clone, or how to get it if already cloned would be useful. I would suggest something like the following:

## Install From Source

Clone the repository using:

	git clone --recurse-submodules https://github.com/wxFormBuilder/wxFormBuilder.git

If the above command was not used, then the following two commands need to be run in your cloned repository:

	git submodule init
	git submodule update

To get submodule updates, run:

	git submodule update --remote

**Comment by sodevel** [comment]
The README.md does mention the older switch `--recursive` for every OS so you should get the submodules. I don't know what other features the newer switch `--recurse-submodules` offers, at least with my git version 2.20.1 i get the same result using both switches. I don't think we should teach people how to use git in the README.md file, this is the job of the git documentation. And IMHO the new option `submodule.recurse true` is a much better way to deal with submodules.

Aynway, did i miss any other file that mentions how to clone this repo? Because in the README.md in the project root all git commands look fine to me, maybe i could update them to use the newer switch, but i don't see any command line that doesn't clone the submodules.

**Comment by Randalphwa** [comment]
Ah, I didn't need to install MYSYS2 so I didn't realize that the cloning instructions were in that block of commands. It does seems odd to me that the git clone instructions aren't presented outside of the various build systems since the command line is platform and build independent. The only reason to give it at all is because of the sub-module -- so if you miss the option for the git clone command, then you end up with a repository that doesn't build until you retrieve the sub-module.

As for the switch itself, I wasn't suggesting a specific switch, just anything that indicates that git clone by itself is unsufficient.
