### ISSUE TITLE
Assertion in some generated code, including wxFB:geninhertclass_gui.cpp

### ISSUE THREAD

**Issue by Randalphwa** [wxFormBuilder/wxFormBuilder#570]
I'm building and running **wxFB** using wxWidgets 3.1.3 debug dlls. I get assertions in **wxFB** when the dialog box is displayed that generates the inherited class code. I also initially got assertions in my own project files when using **wxFB** generated inherit code (this won't happen if the user doesn't select the conflicting style).

The issue is that if a control is a child of a wxVERTICAL sizer, then you get an assertion if the control tries to use any of the vertical alignment styles. Same issue with horizontal alignment styles in a child of a wxHORIZONTAL sizer. Users who don't check an alignment option that is ignored due to the parent sizer alignment won't see the assertion.

I haven't dived into this part of the code base yet, but I would assume fixing this would primarily entail having **wxFB** ignore writing alignment styles that align in the same direction as the parent alignment.

For **wxFB** itself it's slightly more problematic since the geninhertclass_gui.cpp is created from a 1.9 version of the project file. Once **wxFB** doesn't write code that generates the assertions, it could be run on itself -- but that means changing to a newer version of the project file before re-generating the code.

**Comment by sodevel** [comment]
Newer wxWidgets versions perform more validation of input parameters and report errors with assertions. This is quite nice, i found a bunch of these layout errors in our applications as well because of that. But i don't think wxFB should perform these checks as well and especially it should not silently ignore some settings because of that. The validation rules are part of wxWidgets and cannot be accessed programmatically so wxFB needs to implement its own rules and keep them in sync with wxWidgets. Why should we take the burden to validate something on our own that the library validates for us for free?

About your second point, i don't see a big problem there. There is an error in the project file and that can and should be fixed instead of letting the code generation hide that error. Upgrading the version of the project file is also no issue if the current code can process that version :wink:.
