### ISSUE TITLE
Windows - Compile error

### ISSUE THREAD

**Issue by correiadn** [wxFormBuilder/wxFormBuilder#595]
Hi,

I just followed each steps to get the latest version of wxFormBuilder on Windows, but I am getting below error. Any idea what could it be?

../../../src/dbg_stack_trace/stack.cpp:136:23: error: 'bfd_get_section_flags' was not declared in this scope; did you mean 'bfd_set_section_flags'?

![image](https://user-images.githubusercontent.com/17159123/76646086-19495900-6539-11ea-8513-fe0a602f8101.png)

**Comment by rkcity** [comment]
I had same issue about this.
The root cause I found was: binutils rename bfd macro since 2.33: [Reference Here](https://sourceware.org/git/?p=binutils-gdb.git;a=blobdiff;f=bfd/bfd-in.h;h=e55e3e90ba7f8983515c585d6c5bb4154ed11ddd;hp=5a303443501902af4c0e016d351e8234fb9795a6;hb=fd3619828e94a24a92cddec42cbc0ab33352eeb4;hpb=5dfda3562a69686c43aad4fb0269cc9d5ec010d5)
then, i workaround this problem by replace macro name in src\dbg_stack_trace\stack.cpp

**Comment by sodevel** [comment]
Thanks for the info, fixed.

**Comment by max-letters-CAPS** [comment]
unfortunately getting a new error after your fix
![console](https://user-images.githubusercontent.com/63864797/79585318-4d83dc80-80d8-11ea-8da9-b354ea6953ff.png)
In spite of the error above the "wxFormBuilder.exe" is being created BUT when trying to install/open it via same console or file magager I get these system error prompts one after the other
![after opening file](https://user-images.githubusercontent.com/63864797/79585574-a6ec0b80-80d8-11ea-9e14-63d1a9cece63.png)
