### ISSUE TITLE
Updates for README.md for Debian 10

### ISSUE THREAD

**Issue by chucktilbury** [wxFormBuilder/wxFormBuilder#617]
I added a line for dependencies for Debian 10 as follows:
```sh 
sudo apt install libwxgtk3.0-gtk3-dev libwxgtk3.0-dev libwxgtk-media3.0-gtk3-dev libwxgtk-media3.0-dev meson
```

And I added a line so that the app can find the libraries as follows:
```sh
git clone --recursive --depth=1 https://github.com/wxFormBuilder/wxFormBuilder
cd wxFormBuilder
meson _build --prefix $PWD/_install --buildtype=release
ninja -C _build install
ln -s _install/lib/x86_64-linux-gnu/wxformbuilder _install/lib/wxformbuilder
./_install/bin/wxformbuilder
```
These changes were required to get it to work on my system, which is MX Linux 19 (patito feo)

**Comment by chucktilbury** [comment]
I have a PR available.

**Comment by sodevel** [comment]
I am a bit confused, your install line contains the wxWidgets base package and Media package twice just with slightly different names, this doesn't make sense. If Debian uses different package names than ubuntu it should get an own section, just specifying each packege leads to an error message on every platform.

About the symlink, i currently don't favor to add this, simply because the link is platform specific, yours only works on x86_64. Also see #615.
