### ISSUE TITLE
wxGridBagSizer does not grow column in preview

### ISSUE THREAD

**Issue by janos-ijgyarto** [wxFormBuilder/wxFormBuilder#621]
I'm using Version 3.9.0 on Windows 10 (installed through the latest binary). I put together a simple dialog and organized its contents using wxGridBagSizer. The first 2 rows both use 2 columns, while the 3rd and 4th only use 1 column each. I use the `colspan` parameter to make them span across both columns, and I set the 3rd row and 2nd column to be growable. This ensures that the contents of the last row and column take up all the remaining space in the dialog.

The code exported by wxFormBuilder works correctly, I do get the exact layout that I intended. The issue occurs in the preview window in wxFormBuilder. For some reason, the 2nd column does not grow to fill the remaining horizontal space (the text controls should stretch all the way to the right). Am I missing something?

![gridbag](https://user-images.githubusercontent.com/16936534/87475959-896a0780-c61d-11ea-991e-fc488c334d6b.png)

**Comment by sodevel** [comment]
Did you set the wxEXPAND property on the text fields? Because if not, the cells do fill up the whole column but the text fields simply don't grow to fill that space.

With these settings the text fields grow properly in my version, however i am not using that release but the recent master snapshot build against a recent wxWidgets 3.1.x. If it doesn't work for you with these properties set, can you try a recent master snapshot you can download from the Github Actions tab (e.g. https://github.com/wxFormBuilder/wxFormBuilder/suites/909694405/artifacts/10986569)? If such a snapshot also doesn't work then the culprit is wxWidgets 3.0.x (still no other release available in MSYS2) and the only way to solve it is to compile wxFB yourself against a wxWidgets 3.1.x release.

**Comment by janos-ijgyarto** [comment]
> 
> 
> Did you set the wxEXPAND property on the text fields? Because if not, the cells do fill up the whole column but the text fields simply don't grow to fill that space.
> 
> With these settings the text fields grow properly in my version, however i am not using that release but the recent master snapshot build against a recent wxWidgets 3.1.x. If it doesn't work for you with these properties set, can you try a recent master snapshot you can download from the Github Actions tab (e.g. https://github.com/wxFormBuilder/wxFormBuilder/suites/909694405/artifacts/10986569)? If such a snapshot also doesn't work then the culprit is wxWidgets 3.0.x (still no other release available in MSYS2) and the only way to solve it is to compile wxFB yourself against a wxWidgets 3.1.x release.

Yeah, I set that property on all the text fields:

![gridbag](https://user-images.githubusercontent.com/16936534/87558503-16aa6c00-c6b1-11ea-8645-ee463645924b.png)

I'll try compiling a recent version and see if that works.

**Comment by janos-ijgyarto** [comment]
Confirmed, latest build is working correctly.
