### ISSUE TITLE
Migration of old wxFormBuilder file from 2009

### ISSUE THREAD

**Issue by kiplingw** [wxFormBuilder/wxFormBuilder#636]
I have an old FBP file for wxFormBuilder from aeons ago located [here](https://github.com/kiplingw/slither/blob/master/Source/Resources.fbp). My friend @varun-ramraj and I are trying to migrate it to the newer format so that we can build our old [project](https://github.com/kiplingw/slither/). Unfortunately wxFormBuilder chokes badly on it. We also don't have intimate knowledge of the XML schema or how it has been changed over the last decade in order to migrate it by hand. Any help would be much appreciated.

**Comment by sodevel** [comment]
wxFB contains code to convert old project file versions into the current format. Your file has format 1.9 but the conversion code can go down to pre 1.3 (which should be the very first version ever). I don't see any critical big conversion steps from your version onward.

I converted your file myself and there was no issue at all. Granted, i used the latest master snapshot that contains some improvements over the last release (if you don't want to compile yourself and are on Windows you can grab such a recent snapshot from the Actions tab), but even that version should be able to convert your file without error. The converted file looks good so far, but i didn't compile your project.

If you had any issues during the conversion i need more details because for me it works without error.

**Comment by kiplingw** [comment]
@sodevel, thank you for your help. Could you upload here your converted file so I can test it and see whether the code compiles and runs correctly?

**Comment by sodevel** [comment]
I could but i did nothing else than opening the file and pressing the save button, this is nothing you can't do yourself. I used the latest master snapshot so this file WILL NOT work with wxFB 3.9.0.

**Comment by kiplingw** [comment]
Thanks but my package manager does not appear to have wxFormBuilder available. I see that there are Flatpaks available on GitHub, but I prefer for safety and security reasons to use a properly packaged deb. I looked for a PPA, but I only found an [old one](https://launchpad.net/~wxformbuilder/+archive/ubuntu/release) that stopped being maintained after Xenial. Is there a PPA for Focal?
