### ISSUE TITLE
Problems getting the correct control class name

### ISSUE THREAD

**Issue by Micheus** [wxFormBuilder/wxFormBuilder#638]
I've been working in add support to the Erlang language.
Since I started to add code generation for the connect method I started to get some issues.

Here is a fragment of the code I'm getting:
```
	MyFrame1 = wxFrame:new(wx:null(), ?wxID_ANY, "", [{size,{500,300}}, {style,?wxDEFAULT_FRAME_STYLE bor ?wxTAB_TRAVERSAL}]),
	:
	Frame:connect(MyFrame1, move, [{callback, move}]),
	Frame:connect(MyFrame1, show, [{callback, show}]),
	wxButton:connect(M_button1, command_button_clicked, [{callback, onclick}]),
```
Erlang works a little different and we need to use the format as you see above: _**class:connect(var name, event type, options)**_.

Here is the _Frame_ definition in _forms.erlangcode_, translated from the _.cppcode_ file this is the template.
```
	<templates class="Frame">
		<!-- The duplication of these templates is not ideal, but the ripup is too big to be done before version 3 -->
		<template name="base">wxFrame
		</template>
		<template name="cons_call">
			wxFrame:new(wx:null(), $id, $title, [#ifnotnull $pos
												 @{{pos,$pos }, @}
												 #ifnotnull $size
												 @{{size,$size }, @}
												 #ifnotnull $style
												 @{{style,$style #ifnotnull $window_style @{ | $window_style @}}@}
												 #ifnull $style
												 @{ #ifnotnull $window_style
													@{{style,$window_style } @}@}]),
		</template>
		<template name="evt_connect_OnChar">wxFrame:connect($name, char, #option),</template>
		<template name="evt_connect_OnCharHook">wxFrame:connect($name, char_hook, #option),</template>
		<template name="evt_connect_OnKeyDown">wxFrame:connect($name, key_down, #option),</template>
		:
```
The problem is the **class** is not declared as _wxFrame_. Even I declaring the Frame events using wxFrame, the events inherited from _wxWindows_ uses the macro **#class** in its event template. So, instead of I get _wxFrame_ or even _wxWindow_ I'm getting _Frarme_ prefixing the _connect_ function.

All controls in the **Forms** toolbar will cause the same issue.

Does someone has any idea how can I workaround this? 
Thanks in advanced.

**Comment by Micheus** [comment]
By checking more I noticed that is happening for events defined under **_wxTopLevelWindow_** and **_AUI Events_** groups only.

Also, I found that I can read the "correct" control class name on the template **_"base"_**. It exists only for these controls in the **Forms** toolbar.

So, I'm not sure this is the right approach, but I'm using it as a workaround to replace the control class after evaluate the event template - that worked.

**Comment by sodevel** [comment]
Toplevel elements are a bit different than ordinary elements, code generation for them works a bit different. Their class name is kind of virtual (and i think needs to be different from the real class name to prevent duplicate names, at least ``wxPanel`` exists twice, as toplevel element and as ordinary element) and their name attribute is actually their class name.

You quoted the currently only way to solve this issue above, duplication is the key. The toplevel code templates emulate the ``#class`` macro function (which is only needed for the subclass feature) and check for the subclass themself, all possible event handler templates are redefined to override the inherited ones. In C++ there is a similar problem, the connect handler bind at their object, for ordinary elements it is the instantiated object ``$name``, but this doesn't exist for toplevel elements so they have to use ``this``.

You cannot use the ``base`` template to extract the class name inside an event handler template because the language used inside templates cannot read other templates, they can only read information from the object model. Each template is processed as an individual unit.

**Comment by Micheus** [comment]
@sodevel thanks for the explanation. It's a hard task tray to get the whole concept behind the application just reading a few lines of code and without be following the project since it stated.
Also, the fact of Erlang not be a object oriented language forces me to find a way to workaround situations like that.


> You cannot use the base template to extract the class name inside an event handler template because the language used inside templates cannot read other templates, they can only read information from the object model. Each template is processed as an individual unit.

I'm doing that in the source code when handling the events for generation. Once the main devs don't think to change the "base" template behaviour that will not be a problem. 😃
