### ISSUE TITLE
Installing from source, got a compilation error, running exe file "application error". BUT a workaround worked

### ISSUE THREAD

**Issue by AnthonyTheKoala** [wxFormBuilder/wxFormBuilder#644]
Dear wxFormBuilder project,
First, I want to say that I have succesfully installed wxFormBuilder from the binaries. 
Nevertheless, I want to share my experience of installing eventually from source, which produced an error compilation and produced an error on running the program.

**I eventually had the wxFormBuilder program to work without 'correcting the problems'.**

Followed all the instructions under the subheading "Install From Source"as per page https://github.com/wxFormBuilder/wxFormBuilder

(1) Used the Mingw32 shell  used c:/msys64/mingw32/bin 
(2) In the Mingw32 bash window. After make config=release the Mingw32 bash window.

At the stage:
<pre>
==== Building wxFormBuilder (release) ====
creating obj/Release/wxFormBuilder
......
......
wxFormBuilder.rc
 *** Error: Unrecognised option: '--rcflags'
Use wx-config --help for information on command line options.
Linking wxFormBuilder
</pre>

Question what is the '-rcflags' as an unrecognized option?  How do I rectify this, despite similar '-'rcflags' problems for other applications **BUT** did not apply to  wxFormBuilder.

THEN:

(3) YET in my wxFormBuilder installation at  C:\wxFormBuilder\output there was the  wxFormBuilder.exe file.
Double clicking on the wxFormBuilder.exe file 
A dialog box with the title "wxFormBuilder.exe - Application Error"
The information in the dialog box says:  "The application was unable to start correctly (0xc000007b). Click OK to close the application.

(4) In sum, whether compiling from source with "*** Error: unreocgnized option: '--rcflags'  OR double clicking on wxFormBuilder.exe with "Application Error" dialog box", **NONE** of the google-searched problems applied to this program.

Before you say:
 "....why not change the environmental path to include c:\msys64\mingw32\bin...." been there and done that. The errors still occur. I was running the compilation through the Mingw32 windows which uses files in c:\msys64\mingw32.

Despite not rectifying the '-rcflags' compilation problem and the "application error" problems, **I succeeded** in having the wxFormBuilder program working.
Making a console application wxFormBuilder.bat\
<pre>
echo off
path=c:\msys64\mingw32\bin;%path%
c:\wxformbuilder\output\wxformbuilder.exe
exit
</pre>

The result: I got the program to work.

Note again:
* I have built from source, and got an '-rcFlags' error on compilation - I used the Mingw32 bash window. It did not matter whether the environment variable path was set  to c:\msys64\mingw32\bin OR c:\msys64\mingw64\bin!!!!
* when clicking on the wxFormBuilder.exe file, I get the "Application Error" dialog box (X with red background).
* I made a work around by running wxFormBuilder.exe from a batch file. In the wxFormBuilder.bat I made a temporary path to include c:\msys64\mingw32\bin in the path.
* ON THE OTHER HAND - I installed the binaries at https://github.com/wxFormBuilder/wxFormBuilder/releases, particularly the https://github.com/wxFormBuilder/wxFormBuilder/releases/download/v3.9.0/wxFormBuilder_v3.9.0.exe file. NO PROBLEMS, NO NEED TO USE BATCH FILE WORKAROUND.
* I did this report to share and to understand how to 'fix' this problem that I reported.

Other stuff:
* OS: MS WIN 7
* Python 3.8.6
* import wx
wx.__version__
'4.1.0'

Thank you,
Anthony from Sydney

**Comment by sodevel** [comment]
The `--rcflags` error can be ignored, a switch for the resource compiler got renamed, for compatibility reasons the script tries both variants. One variant will always cause that error, this is by design. You should be worried if you see two errors, but in this case the compilation should be terminated with an error anyway.

Your runtime error happens because wxFB depends on some DLL's, some from the MinGW GCC compiler itself and some external libraries. The `bin` directory of your MinGW toolchain contains these DLL's, adding that directory to `PATH` adds this directory to the DLL lookup directories, hence the libraries will be found and wxFB starts. Another solution is to add these DLLs into the directory of `wxFormBuilder.exe`, because this directory is automatically part of the DLL lookup directories. If you examine the release archives you will find all these required DLL's are included in that directory.

So i don't see any error here that needs to be fixed.

**Comment by AnthonyTheKoala** [comment]
Dear Steffen, 
Thank you for your advice. I copied all the *.dll files from the mingw32\bin. Works OK.
I have another 'bug' to report and will be setting up a new topic.
Thanks, 
Closing this topic
Anthony from Sydney
