### ISSUE TITLE
gmake fails on macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by patrickleevers** [wxFormBuilder/wxFormBuilder#665]
Linking wxFormBuilder
    Running post-build commands
    sh ../../../install/macosx/postbuild.sh -c release
    * Collecting dependencies.......
    /!\ WARNING : Cannot resolve path '/usr/lib/libSystem.B.dylib'
    /!\ WARNING : Library libSystem.B.dylib has an incomplete name (location unknown)
    Please specify now the directory where this library can be found (or write 'quit' to abort):

The problem is explained in this thread (today!):
https://developer.apple.com/forums/thread/655588

**Comment by Huskyforce** [comment]
Same Problem here

**Comment by patrickleevers** [comment]
It's looking as if macos support for this project has been abandoned.… A great pity, as Qt's is slowing too and I was hoping for better from wxWidgets.

**Comment by sodevel** [comment]
This project is not part of wxWidgets nor supported by it in any way. Currently there is only one active maintainer and that one has currently no time available. Additionally that maintainer does not have any macOS experience nor access to any macOS based system beside the CI system employed in this project.

Since Apple seems to go the Microsoft way and make their own standards, instead of ranting it would be more productive if someone with macOS experience and/or access to macOS would try to fix this issue and open a PR here.

**Comment by CricYoung** [comment]
[Here](https://wiki.rocrail.net/doku.php?id=cmac-en)
Here is a solution may be can help.
Support Apple M1 chip.
I succeeded after doing exactly what he say.

**Comment by vinidiktov** [comment]
> [Here](https://wiki.rocrail.net/doku.php?id=cmac-en)
> Here is a solution may be can help.
> Support Apple M1 chip.
> I succeeded after doing exactly what he say.

I've tried both the official instructions and the solution that you linked to.

For me, in both cases the resulting app crashes the same way as is described in https://github.com/wxFormBuilder/wxFormBuilder/issues/677

**Comment by sodevel** [comment]
Does this problem still occur when using the new wxwidgets package from homebrew outlined in the updated install instructions?
