### ISSUE TITLE
Minimum wx version

### ISSUE THREAD

**Issue by redtide** [wxFormBuilder/wxFormBuilder#669]
hi, i would like to contribute (again) to this project but i need to know the minimum wxWidgets version required.
About 10 years ago I worked on adding wx2.9 dev support on wxFB (premake, wxPropertyGrid etc), and now I still see some code since then. I wonder if 2.8 and 2.9 stuff can go and support only 3.0+.

**Comment by sodevel** [comment]
wxWidgets < 3.0 is dead, you don't need to worry about this anymore. wxFB itself requires at least wxWidgets 3.0 to be build, there might be some #ifdefs around to support older versions just because no one took the time to remove them. While wxFB shows some bugs when compiled against wxWidgets 3.0, since this is the last released official version wxFB should be at least somehow usable with this version. I build and test wxFB against some recent master snapshot of wxWidgets and this should be the main target. Use #ifdefs if necessary to support wxWidgets 3.0.x.

**Comment by redtide** [comment]
It's fine, I asked mostly because I noticed that there is still some wrong code using `_()` that should be used for translations instead `wxT()`, which in turn is not used anymore.

**Comment by sodevel** [comment]
This is another issue that there are many locations where strings get translated wrongfully. In my opinion ``wxT()`` is still useful, at least on Windows where you cannot really use UTF-8 for narrow strings 😉.

**Comment by redtide** [comment]
I recall from 2.9/3.0 it was not used anymore, see the [docs](https://docs.wxwidgets.org/3.0.5/group__group__funcmacro__string.html#ga437ea6ba615b75dac8603e96ec864160).
