### ISSUE TITLE
Please add UTF8 signature (BOM) when saving the generated class file (by F8).

### ISSUE THREAD

**Issue by vlad-mal** [wxFormBuilder/wxFormBuilder#683]
Please add UTF8 signature (BOM) when saving the generated class file (by F8).
 Otherwise, national characters are displayed incorrectly after assembly in MSVS-2019. Each time for the generated file, I must (in MSVS2019) perform the "Save as encoded ..." operation in order to save the file again. Thank you.

![1](https://user-images.githubusercontent.com/2589195/121064602-79788a80-c7d0-11eb-8fc7-c54b284de6aa.png)
![2](https://user-images.githubusercontent.com/2589195/121064605-7aa9b780-c7d0-11eb-8bc0-2fc5d253d455.png)

**Comment by sodevel** [comment]
Open the project properties and tick the ``use_microsoft_bom`` checkbox in the C++ section, this enables writing of an UTF-8 BOM. Otherwise you might want to consider using the MSVC compiler option ``/source-charset:utf-8``, these days most source files should use this encoding and most files do not include that BOM.

**Comment by vlad-mal** [comment]
Exactly! Everything, with "use_microsoft_bom" checkbox in  is working!
Apologies for the disturbance.
