### ISSUE TITLE
Android dialogs fonts need to be set before objects created

### ISSUE THREAD

**Issue by jongough** [wxFormBuilder/wxFormBuilder#685]
Using wxFormBuilder to provide the base class for all display objects in a multi-platform development it has worked well. But have now added android as one of the supported platforms and issues have arisen with the c++ code that is generated. On android the default font of an object, i.e. dialog box, needs to be set before any child objects, i.e. static text, are created. If this is not done the use of 'SetFont(....)' will set the font of the child objects but the size of these objects will be calculated using the original font size when they were created. 

The wxWidgets manual says, in a round about way, that a dialog box needs to be instantiated first, then SetFont needs to be called to set the default font, then the display objects need to be added to the dialog box. In the current implementation, 3.9.0, this is not possible as the class definition does the child object creation.

I have done a test by changing the code that creates the c++ class to have the instantiation only create the class, and have added a method, create(), which can be used by a child class to create all the objects. This allows for the setting of the default font to something else than the system font.

The original code:
```
ODPropertiesDialogDef::ODPropertiesDialogDef( wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style ) : wxDialog( parent, id, title, pos, size, style )
{
	this->SetSizeHints( wxDefaultSize, wxDefaultSize );
```
The modified code:
```
ODPropertiesDialogDef::ODPropertiesDialogDef( wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style ) : wxDialog( parent, id, title, pos, size, style )
{}
void ODPropertiesDialogDef::Create()
{
	this->SetSizeHints( wxDefaultSize, wxDefaultSize );

```
There needs to be some changes to the wxFormBuilder GUI to allow the user to specify that the 'Create()' method be used or not. There are two possible solutions, either the base class will by default call the 'Create' method and if requested by the user not do so, or generate the extra 3 lines when asked to.

I do not know how to change the GUI to reflect this change or I would submit a pull request.

**Comment by jongough** [comment]
Pull request, #686, generated. New option for wxWindow, create_children, on by default so class calls Create() method. If turned off the derived class will need to call this method to create all the children.

**Comment by sodevel** [comment]
wxWidgets offers two ways to create widgets, either use the constructor with arguments to fully create the widget, or use the default constructor to only create the C++ part and use the Create() method (which always has arguments) to complete the creation. wxFB is using the former method, using the latter is not feasable because all code templates need to be changed.

Your proposal is kind of a mix of the two and uses a method name that is kind of reserved for the two-step creation of wxWidgets. I don't think it is a good idea to use the same name and i am not sure if that approach is even necessary.

I had a similar problem in the past that required kind of the same solution, i had to inject some code into the generated code before additional child elements are added. I wrote a pretty simple plugin that allowed to inject arbitrary code fragments at arbitrary locations. I never released it because sometimes it was not that clear where that fragment would end up and it seemed that wxFB already contained some preparations to add this as an integral part.

I would prefer that solution because it is more versatile and more simple to implement. More detailed comments in the linked PR.

**Comment by jongough** [comment]
The pull has been updated with changes that make this only apply to C++ dialog boxes. No other form elements are affected. The method name has been changed from 'Create()' to 'CreateChildren' to avoid overloading an existing function. The default action will be to create the new method and call it from the instantiation.

Are there any other issues with this process?

**Comment by jongough** [comment]
Two-step creation for dialog boxes solves this issue.
