### ISSUE TITLE
failing to build on ubuntu 18.04.6 LTS, internal build errors, not ubuntu related

### ISSUE THREAD

**Issue by cybork42** [wxFormBuilder/wxFormBuilder#711]
Dear maintainers.

The build installation for ubuntu won't work at all. 
It starts with false directory paths when following the instructions in README or ion github like this:
_cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release -DWXFB_WXWIDGETS_ENABLE_30=ON
CMake Error: The source directory "/tmp/wxformbuilder/wxFormBuilder/_install" does not exist._

When fixing the wrong directory (use "install" instead of "_install") reference, it just reveals the next error:
_CMake Error: The source directory "/tmp/wxformbuilder/wxFormBuilder/install" does not appear to contain CMakeLists.txt._

When you copy "CMakeLists.txt" into the "install" the next complaint is that CMake needs to be 3.21 which I cannot verify to be really needed (seems to be an over-requirement), and so on and so on...
Could you please have a look into this and fix when convenient?

Cheers, Andreas.

**Comment by sodevel** [comment]
The build instructions do work if you meet the requirements. These strange error messages happen because older CMake versions don't understand the `--install-prefix` argument.

CMake 3.21 is required because runtime dependency sets are used. Granted, these are used only on Windows, maybe this can be worked around, however the next lowest requirement is CMake 3.20 because `cmake_path` is used.

Installing CMake 3.21 or later shouldn't be an issue on your system, you should be more worried about the C++17 requirement. I don't know what standard the compiler on your platform supports. AFAIK from the C++ language only attributes are used, your platform might support these. However, from the library filesystem is required, but this could be worked around by using boost::filesystem.

First, you should fix your CMake issue, then you can start working on the possible compiler issue.

**Comment by cybork42** [comment]
You are absolutely right, and I was wrong claiming that cmake version 3.21 would be an over-requirement. My appologies for that.

After compiling this from source and fiddling around with compiler and libraries for some time I started to wonder what makes a wxFormBuilder so urgently need the "hottest stuff" after all. It's not so that wxWidgets are the latest development of all, so why do you need the latest compiler (a later compiler that for wxWidgets themselves?) to build a FormBuilder?

After all the fiddling I decided to clone the old library and used that instead. Thanks a lot for the extremely quick response anyway!
