### ISSUE TITLE
It would be usefull to organize items using folders

### ISSUE THREAD

**Issue by hobbitdev** [wxFormBuilder/wxFormBuilder#718]
### Discussed in https://github.com/wxFormBuilder/wxFormBuilder/discussions/717

<div type='discussions-op-text'>

<sup>Originally posted by **hobbitdev** January 11, 2022</sup>
Hi at all

In case of a huge wxFormBuilder project, it would be usefull to organize items using folders, like the picture below.
Nothing special, only a normal way to keep the project tidy up.
What do you think about it, could it be accepted as a new feature to introduce starting from the new release ?

![image](https://user-images.githubusercontent.com/33904565/148948781-32b2cd23-11e2-47ae-83d9-a2adc4c8214d.png)

Best regards
Rossano
</div>

**Comment by sodevel** [comment]
As C++ only user i don't see the need for such a feature. Since each project file results in one header/source file such huge project files are counter productive because the change of only one component results in recompilation of all components and elements that depend on these. That's why i have a lot of project files instead which mostly contain one top level element and sometimes some closely related others.

This might be different for the other supported languages (is anything else beside Python still in use these days?). But i'm afraid this feature is not so easy to implement. Since this information needs to be stored in the project file, it either needs to be part of the current datamodel or needs to be stored as something additional inside the file. For easy creation of these groups i think they should be added as an additional component that can attach below the project element and accept only other elements of its own type and top level elements. But then also the generators see these components and they have to ignore them, not sure if this is possible by adding empty templates or if they need to be filtered out explicit.

**Comment by hobbitdev** [comment]
Thank you @sodevel for your replay. 

Let me try to go ahead with this small discussion, owever please don't get me wrong, my first intention is try to better understand wxFB and how to use it in the best way, I definitely don't want to criticize your great work.

You say, " Since each project file results in one header/source file such huge project files are counter productive ... "
As I see it, this is due to the way wxFormBuilder was born, if wxFB could generate for each element a single header and its implementation file,  this wouldn't happen.
It seems no so complicated to implement such kind of option, as I've noticed wxFB is already able to show the single header and the single implementation code for each item in wxFB project.

Since I've been using C++ language, and if I observe how other programmers organize their projects, for each single object the common approach is to create a single header file plus its implementation file.

The way wxFB creates objects files, seems a kind of exception of the not written common rule to separete objects in files.
Could you please explain the benefits related to have a single header+implementation file instead ?

In my opinion if wxFB could create separeted files, it would result even more scalable tool and adaptive to every kind of approach.
With "approach" I mean using a single project file, a single header/source instead of many and vice versa.

Best regards
Rossano

**Comment by sodevel** [comment]
> As I see it, this is due to the way wxFormBuilder was born, if wxFB could generate for each element a single header and its implementation file, this wouldn't happen. It seems no so complicated to implement such kind of option, as I've noticed wxFB is already able to show the single header and the single implementation code for each item in wxFB project.

Actually it is complicated. Currently the filename of the generated files (header + impementation) is specified at project level, this property is also used for certain resource loading types. If each top level project should end up in an own file, this property needs to move to these elements instead. This requires changes of the affected resource loading types, the generation process and also the generate implementation process.

Another question is, there is more than just C++ (granted, probably only Python is of relevance), is that layout of benefit for these targets or does it hurt? Also i think to remember some of the other languages can add certain "launcher" code to enable easier usage of the components, whats happens if they are scattered around multiple files, does this need to be adapted as well?

> Since I've been using C++ language, and if I observe how other programmers organize their projects, for each single object the common approach is to create a single header file plus its implementation file.
> 
> The way wxFB creates objects files, seems a kind of exception of the not written common rule to separete objects in files. Could you please explain the benefits related to have a single header+implementation file for many objects instead ?

Well, this approach does not scale well. C++ is not Java and luckily doesn't enforce this, following that approach strictly has the disadvantage that in huge projects you get a lot of compilation units which results in longer compilation times. It is better to group related (smaller) classes / functions into one compilation unit to improve compilation times.


In general, this looks like a lot of work for something that can already be realized by simply using multiple project files.

**Comment by hobbitdev** [comment]
Thank you @sodevel for your time and explanations.
Definitely I can survive even with a single header/implementation file :)
Even though simply being able to organize items in groups, would be appreciated and useful.

Once again thank you

Best regards
Rossano
