### ISSUE TITLE
Windows Install for MSYS

### ISSUE THREAD

**Issue by tester0077** [wxFormBuilder/wxFormBuilder#731]
I want to install the build system under Win 10 and have just installed MSYS as per: as per: https://www.msys2.org/

When I execute  in the MSYS shell - `pacman -S ${MINGW_PACKAGE_PREFIX}-toolchain ${MINGW_PACKAGE_PREFIX}-cmake
`

as per: https://github.com/wxFormBuilder/wxFormBuilder, I get:
```
arnold@Red MSYS ~
$ pacman -S ${MINGW_PACKAGE_PREFIX}-toolchain ${MINGW_PACKAGE_PREFIX}-cmake
pacman: unknown option -- a

arnold@Red MSYS ~

```
How can I proceed?
 where did I go wrong?

**Comment by sodevel** [comment]
You are using the wrong shell environment, you have to use a MINGW32 or MINGW64 environment, not MSYS. The MSYS2 system supplies multiple shell scripts to launch different environments, just use one of the MINGW variants.

**Comment by tester0077** [comment]
Thank you.
That got me further along - FWIW, I am a newb to MSYS etc and have used CMake only rarely quite some time ago.

I am stuck after getting this error from the first CMake comamnd
```

CMake Error at C:/msys64/mingw32/share/cmake-3.22.3/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost: Found unsuitable version "1.70.0", but required is at
  least "1.71.0" (found C:/local/boost_1_70_0, )
Call Stack (most recent call first):
  C:/msys64/mingw32/share/cmake-3.22.3/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  C:/msys64/mingw32/share/cmake-3.22.3/Modules/FindBoost.cmake:2375 (find_package_handle_standard_args)
  CMakeLists.txt:170 (find_package)
```

**Comment by sodevel** [comment]
I am not using MSYS2 myself so i have only limited knowledge about it. As can be seen in your log, CMake picks up a Boost installation in a fairly non-standard location `C:/local/boost_1_70_0`. This is not the Boost of the MSYS2 installation. Most probably you have set some environment variables in your system that CMake examines, either something general like `PATH` or maybe something specific for CMake like `CMAKE_PREFIX_PATH`.

**Comment by tester0077** [comment]
After giving up on MSYS, I have been able to manually build a MSVC 2019 sln file and it compiles, after I fiddled a couple of things to make up for the pre-install/config step, which understandably did not run.
As for the boost libraries I, I compiled the lot manually and that issue is no longer a problem.
As I am not familiar at all with these config steps  - I very much stick to the M$ world - I'd be very grateful, if someone can point me to where the @ variable in revision.cpp.in are updated - presumably as part of converting revision.cpp.in -> revision.cpp

**Comment by sodevel** [comment]
I am not sure if i understand everything correctly that you have written, but instead of fixing your system environment, you "reverse engineered" the CMake files to write a MSVC project manually? CMake can just generate this for you, just select a different generator! However, without fixing your system environment first, you most probably will suffer the same issue, CMake will pick up the wrong Boost library.

The variable substitution is done by CMake, the version during configure time, the revision during the build. The corressponding code is part of the CMake file inside the `src` directory, it uses CMake "library" files of the `cmake` directory. However, to save yourself A LOT of time, just drop you custom project files and use CMake to generate them.

On Windows you face to problems building code:

1. Find libraries at build time
2. Find DLLs at runtime

CMake has a solution for 1., you need to take care of 2. yourself (or just use the `install` target, the wxFB CMake files collect all dependencies and create a self-contained install tree, except compiler runtime, this needs to be installed on the system).

The most simple way to solve 1. is to use the `CMAKE_PREFIX_PATH` environment variable, point it to the root directory of a Linux-Like directory tree containing your libraries. The Boost install target does create such a directory tree, the wxWidgets CMake build as well (the prebuild wxWidgets build files use a different directory layout, but CMake does understand that as well). To solve 2., you can put the `bin` and `lib` directory of that directory tree on the `PATH`.

**Comment by tester0077** [comment]
The current status of my manual installation: wxFB builds and runs, but it cannot find the plugins directories and, unless I fudge the catch to ignore this error, is simply exits with a a very useless error popup.
If I ignore this error ( replace the catch at database.cpp where it is trying to load the plugins dlls) and return from this function rather the throwing an error, the app starts and looks good except that for some of the component palette notebook pages, the top panel has the icons, for others they are missing. The whole panel is not sized as expected, but the icons which are visible do seem to react as expected, as far as I can tell.
Quite evidently, the code loading the plugins (the boost file system code, no doubt) needs some path prefix, which I have not determined as yet.
I will try to follow your suggestion to use the CMake system, though, I have not had the best of success using it in the past. 
For the times where it runs well, I have had success in using the MSVC builds, but for several cases, there were missing conditions or ???? whatever which never let the CMake system work well. Hence, I have stayed away from it and have little background using it. :-(

**Comment by tester0077** [comment]
Updated my Cmake  to 3.23.1, created a build directory and started CMake with the base Cmakelist.txt in the wxFB root - using a clean copy of the latest zip from github.
First hiccup: CMake is looking for a mono build of wxWidgets, but the current copy I have installed from the installer seems to use individual libraries. - this was an easy fix, just uncheck the relevant check box.
Second snag: 
```
CMake Error at CMakeLists.txt:205 (add_subdirectory):
  The source directory

    D:/pkg/wx/MSVC2019/_3.1.4_2019/wxFormBuilder-CM/wxFormBuilder-master/third_party/ticpp

  does not contain a CMakeLists.txt file.
```
This issue, I have no idea how to fix. 
The directory third_party directory does not have this file.
2 of the subdirectories - md5 & stack_trace do, but the 3rd - ticpp is empty

Please advise. :-)

**Comment by sodevel** [comment]
From the release notes:

>If you need a source code archive, do not use the automatic created archives, they lack the required submodules. Instead, use the attached full source code archives.

So either you download one of the `source-full` archives or use the recommended way and just `clone --recursive` the repo to get the `ticpp` submodule.

**Comment by tester0077** [comment]
Thank you, sodevel. :-)
Following you recommendation, I cloned the Github code and ran CMake 3.23.1 against it.
After deselecting the wxWidgets mono build, I was left with one issue:
wxWidgets_wxrc_EXECUTABLE-NOTFOUND
Ignoring that, (it does not seem becessary" I generated the MSVC 2019  sln file and used it to compile the app.
Only one issue popped up, I needed to include the library
D:\MSVC2019\wxWidgets-3.1.4\lib\vc_x64_lib\wxscintillad.lib
for both the main app & wxFB-addition for the linker.
------------------------
As for the information in the release notes, IMO, that sort of information would be more useful in the readme text.
