### ISSUE TITLE
OnDropFiles event is missing on Windows

### ISSUE THREAD

**Issue by n00b87** [wxFormBuilder/wxFormBuilder#749]
I am using wxFormBuilder 3.10.1 on both Windows and Linux. On Linux, the OnDropFiles event shows up under Other Events but it is completely missing on Windows.

To be more specific, I am trying to add this event to a wxAuiNotebook.

**Comment by sodevel** [comment]
There is no platform specific filtering of this event, most probably you are using different wxFormBuilder builds. You can see the complete build number on the about screen, if the numbers before the first dash are the same, the bigger number directly behind the first dash denotes a newer version. And if that number is zero, you are using a release build. At least on Linux it can't be zero because this feature was added after the latest release.

**Comment by n00b87** [comment]
@sodevel Thanks for the reply. It was 3.10.1-0 on Windows. I downloaded both of them from the latest releases on github so I assumed they would both be for the same version. I already worked around my issue by adding the OnDropFiles event in the constructor of my derived class.

I will close this issue.
