### ISSUE TITLE
Is it possible to build using wxwidgets 3.2 Msys2

### ISSUE THREAD

**Issue by alex290** [wxFormBuilder/wxFormBuilder#775]
Trying to assemble according to the instructions via Cmake Msys2 wxWidgets3.2 gives an error:
```
 Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1.2")
```
![](https://i.imgur.com/FY1ZAQP.png)

Although the instructions say version 3.2
Is there if it is possible to build for version 3.2?

**Comment by sodevel** [comment]
Yes, it is possible to build with wxWidgets 3.2 on MSYS2, the GitHub CI is doing this already since some time.

Is your MSYS2 up to date? Which version of wxFB are you building? Current master branch or something else? And which version of CMake are you using? Only fairly new versions of CMake can find wxWidgets 3.2. Do you have more than one wxWidgets version installed in your MSYS2 environment?

**Comment by alex290** [comment]
1. Yes MSYS2 has been updated to the latest version.

2. wxFB tried to rip off the last branch 
`git clone - recursive https://github.com/wxFormBuilder/wxFormBuilder `

3. CMake 3.25

4. wxWidgets costs only 3.2.2

**Comment by alex290** [comment]
And all the assembly was successful. Everything is fine. There was a packet conflict in Msys2.
