### ISSUE TITLE
crash generating C++ code for wxSplitterWindow

### ISSUE THREAD

**Issue by DRNadler** [wxFormBuilder/wxFormBuilder#836]
Maybe I'm not using wxFormBuilder (3.9.0) correctly?
I want to create a wxSplitterWindow containing a couple of panels.
Trying to do this I got error messages:

1. **Impossible to create the object. Did you forget to add a sizer/parent object?** The parent object is a frame which should be OK? Anyway I added a wxBoxSizer, then added the splitter as its child.
2. When I added the splitter as above, I got an error about **missing child windows**, so I added a couple child panels

When I tried to generate code, wxFormBuilder crashed (screenshot below).
![wxFormBuilder_wxSplitterWindow_crash](https://github.com/user-attachments/assets/350c44a5-3b98-431a-a6a9-8f09197b9021)

Creating a new project and minimal frame - bo
[wxLogAnalyzer_fbp.zip](https://github.com/user-attachments/files/16567696/wxLogAnalyzer_fbp.zip)
x sizer - splitter - 2 panels worked OK.
But inside my project's main frame it failed.
I've attached my project so you can reproduce the problem I hope....
Thanks!
Best Regards, Dave

**Comment by sodevel** [comment]
First of all, why are you using an almost 6 years old version of wxFB instead of a current release?

About 1.), wxFB supports sizer-based layouts only, you have to set a sizer to a toplevel element to add anything to it unless you are using AUI, this works differently and doesn't use sizers on the managed window.

About 2.), a wxSplitterWindow must have one or two child windows.

I have used your attached project with a current master snapshot of wxFB, i couldn't produce a crash. But that project does not contain a wxSplitterWindow so i have added one. But again, no crash. So whatever your issue is, it seems to be fixed in the latest release.

Please try your project again with the latest release of wxFB.

**Comment by DRNadler** [comment]
Thanks, I've updated to latest release...
